const stopInput = document.querySelector(".stop-input");
const submitButton = document.querySelector(".submit-button");

function autocomplete(input, array) {
  let currentFocus;
  input.addEventListener("input", function (e) {
    let list,
      line,
      i,
      val = this.value;
    closeAllLists();
    if (!val) {
      return false;
    }
    currentFocus = -1;
    list = document.createElement("DIV");
    list.setAttribute("id", this.id + "autocomplete-list");
    list.setAttribute("class", "autocomplete-items");
    this.parentNode.appendChild(list);
    for (i = 0; i < array.length; i++) {
      if (
        latinize(array[i].substr(0, val.length).toUpperCase()) ==
        latinize(val.toUpperCase())
      ) {
        line = document.createElement("DIV");
        line.innerHTML =
          "<strong>" + array[i].substr(0, val.length) + "</strong>";
        line.innerHTML += array[i].substr(val.length);
        line.innerHTML += "<input type='hidden' value='" + array[i] + "'>";
        line.addEventListener("click", function (e) {
          input.value = this.getElementsByTagName("input")[0].value;
          submitButton.click();
          closeAllLists();
        });
        list.appendChild(line);
      }
    }
  });
  /*execute a function presses a key on the keyboard:*/
  input.addEventListener("keydown", function (e) {
    let listIndex = document.getElementById(this.id + "autocomplete-list");
    if (listIndex) listIndex = listIndex.getElementsByTagName("div");
    if (e.keyCode == 40) {
      currentFocus++;
      addActive(listIndex);
    } else if (e.keyCode == 38) {
      currentFocus--;
      addActive(listIndex);
    } else if (e.keyCode == 13) {
      if (currentFocus > -1) {
        if (listIndex) listIndex[currentFocus].click();
      }
    }
  });

  /*a function to classify an item as "active":*/
  function addActive(listIndex) {
    if (!listIndex) return false;
    removeActive(listIndex);
    if (currentFocus >= listIndex.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = listIndex.length - 1;
    listIndex[currentFocus].classList.add("autocomplete-active");
  }

  /*a function to remove the "active" class from all autocomplete items:*/
  function removeActive(listIndex) {
    for (let i = 0; i < listIndex.length; i++) {
      listIndex[i].classList.remove("autocomplete-active");
    }
  }

  /*close all autocomplete lists in the document,
    except the one passed as an argument:*/
  function closeAllLists(element) {
    let items = document.getElementsByClassName("autocomplete-items");
    for (let i = 0; i < items.length; i++) {
      if (element != items[i] && element != input) {
        items[i].parentNode.removeChild(items[i]);
      }
    }
  }
  /*execute a function when someone clicks in the document:*/
  document.addEventListener("click", function (e) {
    closeAllLists(e.target);
  });
}

const busStops = [
  "1 Maja 01",
  "23 Marca 01",
  "23 Marca 02",
  "3 Maja 01",
  "3 Maja 02",
  "3 Maja 03",
  "49 Baza Lotnicza 01",
  "49 Baza Lotnicza 02",
  "Abrahama 01",
  "Abrahama 02",
  "Aeroklub Gdański 01",
  "Aeroklub Gdański 02",
  "Agrarna 01",
  "Agrarna 02",
  "Agrarna 03",
  "Akademia Muzyczna 01",
  "Akademia Muzyczna 02",
  "Akademia Muzyczna 03",
  "Akademia Muzyczna 04",
  "Aksamitna 01",
  "Andruszkiewicza 02",
  "Anyżowa 01",
  "Anyżowa 02",
  "Archikatedra Oliwska 01",
  "Astronautów 01",
  "Astronautów 02",
  "Azaliowa 01",
  "Bajana 01",
  "Bajana 02",
  "Bajana 03",
  "Bajki 01",
  "Barniewicka 01",
  "Barniewicka 02",
  "Barniewicka 03",
  "Bartnicza 01",
  "Batalionów Chłopskich 01",
  "Batalionów Chłopskich 02",
  "Baza Hallera T1",
  "Baza Manipulacyjna 01",
  "Baza Manipulacyjna 02",
  "Baśniowa 01",
  "Baśniowa 02",
  "Bażyńskiego 01",
  "Bażyńskiego 02",
  "Bażyńskiego 04",
  "Bażyńskiego 05",
  "Bażyńskiego 06",
  "Bażyńskiego 07",
  "Belgradzka 01",
  "Belgradzka 02",
  "Belgradzka 03",
  "Bema 01",
  "Beniowskiego 01",
  "Beniowskiego 02",
  "Benzynowa 01",
  "Benzynowa 02",
  "Biała 01",
  "Biały Dwór 01",
  "Biały Dwór 02",
  "Biblioteka Główna UG 01",
  "Biblioteka Główna UG 02",
  "Bitwy pod Płowcami 02",
  "Bitwy pod Płowcami 04",
  "Biwakowa 01",
  "Biwakowa 02",
  "Bobrowa 01",
  "Bobrowa 02",
  "Bogatka I 01",
  "Bogatka I 02",
  "Bogatka II 01",
  "Bogatka II 02",
  "Bogatka III 01",
  "Bogatka III 02",
  "Boguckiego 01",
  "Boguckiego 02",
  "Bohaterów Monte Cassino 01",
  "Bora Komorowskiego 01",
  "Bora Komorowskiego 02",
  "Bora Komorowskiego 04",
  "Bora Komorowskiego 05",
  "Bora Komorowskiego 06",
  "Bora Komorowskiego 07",
  "Borowiecka 01",
  "Borowiecka 02",
  "Brama Nizinna 01",
  "Brama Nizinna 02",
  "Brama Oliwska 01",
  "Brama Oliwska 02",
  "Brama Oliwska 03",
  "Brama Oliwska 04",
  "Brama Oruńska 01",
  "Brama Oruńska 02",
  "Brama Wyżynna 01",
  "Brama Wyżynna 02",
  "Brama Wyżynna 03",
  "Brama Wyżynna 04",
  "Brama Wyżynna 05",
  "Brama Żuławska 01",
  "Brama Żuławska 02",
  "Brama Żuławska 03",
  "Brama Żuławska 04",
  "Brama Żuławska 05",
  "Bratki 01",
  "Brodwino 02",
  "Brodwino Szkoła 01",
  "Broniewskiego 01",
  "Broniewskiego 02",
  "Brzegowa 01",
  "Brzegowa 02",
  "Brzeźno 01",
  "Brzeźno 02",
  "Brzeźno 03",
  "Brzeźno 04",
  "Brzeźno 05",
  "Brętowo PKM 01",
  "Brętowo PKM 02",
  "Brętowo PKM 03",
  "Brętowo PKM 04",
  "Budapesztańska 01",
  "Budapesztańska 02",
  "Budapesztańska 03",
  "Budapesztańska 04",
  "Budzysza 01",
  "Bursztynowa 01",
  "Bursztynowa 02",
  "Bysewo 01",
  "Bysewo 02",
  "Bysewo 03",
  "Bysewo 04",
  "Bysewo 05",
  "Błonia 01",
  "Błonia 02",
  "Cebertowicza 01",
  "Cebertowicza 02",
  "Centrostal 01",
  "Centrostal 02",
  "Centrum Medycyny Inwazyjnej 01",
  "Centrum Medycyny Inwazyjnej 02",
  "Centrum Nadawcze RTV 01",
  "Centrum Nadawcze RTV 02",
  "Centrum Onkologii 04",
  "Charpentiera 01",
  "Charpentiera 02",
  "Chałubińskiego 01",
  "Chałubińskiego 02",
  "Chałubińskiego 03",
  "Chałubińskiego 04",
  "Chełm Cienista 01",
  "Chełm Cienista 02",
  "Chełm Cienista 03",
  "Chełm Witosa 01",
  "Chełm Witosa 02",
  "Chmielna 01",
  "Chmielna 02",
  "Chmielna 03",
  "Chmielna 04",
  "Chodowieckiego 01",
  "Chodowieckiego 02",
  "Chopina 01",
  "Chopina 01",
  "Chopina 02",
  "Chrobrego 01",
  "Chrobrego 02",
  "Chrzanowskiego 03",
  "Chwaszczyno 01",
  "Chwaszczyno 02",
  "Chłodna 02",
  "Chłopska 01",
  "Ciasna 01",
  "Ciasna 02",
  "Cicha (Cmentarz) 01",
  "Cicha (Cmentarz) 02",
  "Cieszyńskiego 01",
  "Cieszyńskiego 02",
  "Cieszyńskiego 03",
  "Cieszyńskiego 04",
  "Ciołkowskiego 01",
  "Cmentarz Oliwski 01",
  "Cmentarz Oliwski 02",
  "Cmentarz Srebrzysko 01",
  "Cmentarz Srebrzysko 02",
  "Cmentarz Łostowicki 01",
  "Cmentarz Łostowicki 02",
  "Cygańska Góra 03",
  "Cygańska Góra 04",
  "Cyprysowa 02",
  "Cystersów 01",
  "Cystersów 02",
  "Czarny Dwór 01",
  "Czarny Dwór 02",
  "Czarny Dwór 03",
  "Czermińskiego 01",
  "Czermińskiego 02",
  "Czerwony Dwór 01",
  "Czerwony Dwór 02",
  "Czerwony Dwór 03",
  "Czerwony Dwór 04",
  "Czerwony Dwór 05",
  "Czyżewskiego 01",
  "Damroki 01",
  "Damroki 02",
  "De Plelo 01",
  "De Plelo 02",
  "Derdowskiego 01",
  "Derdowskiego 02",
  "Dickensa 01",
  "Do Zdroju 07",
  "Do Zdroju 08",
  "Dobra 01",
  "Dobrowo 01",
  "Dobrowo 02",
  "Dobrowo 04",
  "Dobrowolskiego 01",
  "Dobrowolskiego 02",
  "Dolna 01",
  "Dolne Młyny 01",
  "Dolne Młyny 02",
  "Dom Pomocy Społecznej 01",
  "Dom Pomocy Społecznej 02",
  "Droszyńskiego 01",
  "Droszyńskiego 02",
  "Drwęcka (n/ż) 01",
  "Drzewieckiego 01",
  "Drzewieckiego 02",
  "Drzymały 01",
  "Dworkowa 01",
  "Dworska 02",
  "Dworska 03",
  "Dworska 04",
  "Dworzec Główny 01",
  "Dworzec Główny 02",
  "Dworzec Główny 05",
  "Dworzec Główny 07",
  "Dworzec Główny 08",
  "Dworzec Główny 10",
  "Dworzec Główny 11",
  "Dworzec Główny 12",
  "Dworzec Główny 13",
  "Dworzec Główny 14",
  "Dworzec Główny 18",
  "Dwór Ferberów 01",
  "Dywizjonu 303 01",
  "Dziewicza 01",
  "Dziewicza 02",
  "Dąbrowa Centrum 01",
  "Dąbrowa Centrum 04",
  "Długie Ogrody 01",
  "Elbląska 05",
  "Elfów 01",
  "Elfów 02",
  "Emaus 01",
  "Emaus 02",
  "Emaus 03",
  "Emaus 04",
  "Emilii Plater 01",
  "Emilii Plater 02",
  "Emilii Plater 04",
  "Fabryczna 01",
  "Fabryczny 01",
  "Faktoria 01",
  "Faktoria 02",
  "Falista 01",
  "Falista 02",
  "Falowa 01",
  "Falowa 02",
  "Firoga 01",
  "Firoga 02",
  "Focha 01",
  "Focha 02",
  "Forsycji 01",
  "Forsycji 02",
  "Galeria Bałtycka 01",
  "Galeria Bałtycka 02",
  "Galeria Bałtycka 03",
  "Galeria Bałtycka 04",
  "Galeria Bałtycka 05",
  "Galeria Bałtycka 06",
  "Galeria Bałtycka 07",
  "Gdańska 01",
  "Gdańska 03",
  "Gdańska 12",
  "Gdyńska 01",
  "Gdyńska 02",
  "Geodetów 01",
  "Giełda Towarowa 01",
  "Giełda Towarowa 02",
  "Gospody 01",
  "Gospody 02",
  "Gostyńska Szpital 01",
  "Gostyńska Szpital 02",
  "Goyki 01",
  "Gościnna 01",
  "Gościnna 02",
  "Gościnna 03",
  "Grabowskiego 01",
  "Grand Hotel 02",
  "Gronostajowa 01",
  "Gronostajowa 02",
  "Grudziądzka 01",
  "Grudziądzka 02",
  "Grudziądzka 03",
  "Grudziądzka 04",
  "Grudziądzka 05",
  "Grunwaldzka 01",
  "Góralska 01",
  "Góralska 02",
  "Górecka 01",
  "Górecka 02",
  "Górki Wschodnie 01",
  "Górki Wschodnie 02",
  "Górki Zachodnie 01",
  "Górskiego 01",
  "Górskiego 02",
  "Gęsia 01",
  "Głucha 01",
  "Głucha 02",
  "Głęboka 01",
  "Głęboka 01.",
  "Głęboka 02",
  "Głęboka 02.",
  'Hala "Olivia" 01',
  'Hala "Olivia" 02',
  "Harfowa 01",
  "Harfowa 02",
  "Helska 01",
  "Helska 02",
  "Hestii 01",
  "Hestii 02",
  "Hevelianum 01",
  "Hevelianum 02",
  "Hokejowa 01",
  "Hokejowa 02",
  "Hospicjum 01",
  'Hotel "Marina" 01',
  'Hotel "Marina" 02',
  "Hucisko 01",
  "Hucisko 02",
  "Hucisko 03",
  "Hucisko 04",
  "Hynka 01",
  "Hynka 02",
  "Ikara 01",
  "Ikara 03",
  "Ikara 04",
  "Instal 02",
  "Inżynierska 01",
  "Inżynierska 02",
  "Iławska 01",
  "Iławska 02",
  "Jabłoniowa Osiedle 01",
  "Jabłoniowa Osiedle 02",
  "Jagiellońska 01",
  "Jagiellońska 02",
  "Jagiełły 01",
  "Jagiełły 02",
  "Jana Pawła II 01",
  "Jana Pawła II 02",
  "Jana z Kolna 01",
  "Jankowo 01",
  "Jarowa 01",
  "Jarowa 02",
  "Jasia i Małgosi 01",
  "Jasia i Małgosi 02",
  "Jasień Działki 01",
  "Jasień Działki 02",
  "Jasień PKM 01",
  "Jasień Pólnicy 01",
  "Jasieńska 01",
  "Jasieńska 02",
  "Jasieńska 03",
  "Jaworowa 01",
  "Jaworowa 02",
  "Jaworzniaków 01",
  "Jaworzniaków 02",
  "Jaśkowa Dolina 01",
  "Jaśkowa Dolina 02",
  "Jaśkowa Dolina 03",
  "Jaśkowa Dolina 04",
  "Jaśkowa Dolina 05",
  "Jednorożca 01",
  "Jednorożca 02",
  "Jeleniogórska 01",
  "Jeleniogórska 02",
  "Jelitkowo 02",
  "Jelitkowo 03",
  "Jelitkowo 04",
  "Jelitkowo 05",
  "Jelitkowo 06",
  "Jelitkowo 90",
  "Jelitkowo Kapliczna 01",
  "Jelitkowo Kapliczna 02",
  "Jelitkowo Kapliczna 03",
  "Jesionowa 01",
  "Jesionowa 02",
  "Jeziorowa 01",
  "Jeziorowa 02",
  "Jodowa 01",
  "Jodowa 02",
  "Junaków 02",
  "Kaczeńce - Sienna 01",
  "Kaczeńce 01",
  "Kaczeńce 02",
  "Kaczeńce 03",
  "Kaczeńce 04",
  "Kameliowa 01",
  "Kameliowa 02",
  "Kamienna Grobla 01",
  "Kamienny Potok SKM 02",
  "Kampinoska 01",
  "Kanałowa 01",
  "Kanałowa 02",
  "Karczemki 01",
  "Karczemki 02",
  "Karczemki 03",
  "Karskiego 01",
  "Karskiego 02",
  "Kartuska 01",
  "Kartuska 02",
  "Karwieńska 01",
  "Karwieńska 02",
  "Karwiny PKM 02",
  "Karwiny PKM 05",
  "Karwiny Tesco 01",
  "Karwiny Tesco 02",
  "Kasztanowa 01",
  "Kasztanowa 01",
  "Kasztanowa 02",
  "Kasztelańska 01",
  "Kasztelańska 02",
  "Kempingowa 01",
  "Kempingowa 02",
  "Keplera 01",
  "Keplera 02",
  "Kielecka 01",
  "Kielecka 02",
  "Kiełpino - Szkoła 01",
  "Kiełpino - Szkoła 02",
  "Kiełpino Górne 01",
  "Kilińskiego 01",
  "Kilińskiego 02",
  "Kliniczna 01",
  "Kliniczna 02",
  "Klonowa 01",
  "Klonowa 02",
  "Klonowicza 01",
  "Klonowicza 02",
  "Knyszyńska 01",
  "Kochanowskiego 01",
  "Kokoszki - Poczta 01",
  "Kokoszki - Poczta 02",
  "Kokoszki 04",
  "Kolberga 02",
  "Kolonia Mysia 01",
  "Kolonia Mysia 02",
  "Kolonia Uroda 01",
  "Kolonia Uroda 02",
  "Kolorowa 01",
  "Kolorowa 02",
  "Kolumba 01",
  "Kolumba 02",
  "Kolumba 03",
  "Kolumba 04",
  "Komarowo 01",
  "Konkordii 01",
  "Konkordii 02",
  "Kontenerowa 01",
  "Kontenerowa 02",
  "Kopalniana 01",
  "Korczaka 01",
  "Korczaka 02",
  "Korty Tenisowe 02",
  "Kosmonautów 01",
  "Kosmonautów 02",
  "Koziorożca 01",
  "Koziorożca 02",
  "Kołobrzeska 01",
  "Kołobrzeska 02",
  "Kołobrzeska 03",
  "Kołobrzeska 04",
  "Kołobrzeska 05",
  "Kołobrzeska 06",
  "Kościuszki 01",
  "Kościuszki 02",
  "Kościuszki 03",
  "Kościuszki 04",
  "Kościuszki 05",
  "Krasickiego 01",
  "Krasickiego 02",
  "Krasickiego 02.",
  "Krasickiego 03",
  "Kraszewskiego 02",
  "Krynicka 01",
  "Krynicka 02",
  "Krzemowa 01",
  "Królewskie Wzgórze 01",
  "Królewskie Wzgórze 02",
  "Królewskie Wzgórze 03",
  "Kręta 01",
  "Kręta 02",
  "Ku Ujściu 01",
  "Ku Ujściu 02",
  "Ku Ujściu 04",
  "Ku Ujściu 05",
  "Kujawska 01",
  "Kujawska 02",
  "Kurpińskiego 01",
  "Kurpińskiego 02",
  "Kwiatowa 01",
  "Kwiatowa 02",
  "Kępna 01",
  "Kępna 02",
  "Kłosowa 01",
  "Latarnia Morska 01",
  "Latarnia Morska 02",
  "Lawendowe Wzgórze 01",
  "Lawendowe Wzgórze 03",
  "Lazurowa 01",
  "Lazurowa 02",
  "Legionów 01",
  "Legionów 02",
  "Legionów 03",
  "Legionów 04",
  "Legionów 05",
  "Lenartowicza 01",
  "Lenartowicza 01.",
  "Lenartowicza 02",
  "Lenartowicza 02.",
  "Lessowa 01",
  "Lessowa 02",
  "Lessowa 03",
  "Lessowa 04",
  "Leszczynowa 01",
  "Leszczynowa 02",
  "Leszczyńskich 01",
  "Leszczyńskich 02",
  "Leszczyńskich 03",
  "Leśna Góra - Przychodnia 01",
  "Leśna Góra - Przychodnia 02",
  "Leśna Góra 01",
  "Liliowa 01",
  "Liliowa 02",
  "Lipowa 01",
  "Lipowa 02",
  "Lipuska 01",
  "Lubowidzka 01",
  "Lubowidzka 02",
  "Lwowska 01",
  "Maki 01",
  "Malczewskiego 01",
  "Malczewskiego 02",
  "Marsa 01",
  "Marsa 02",
  "Marynarki Polskiej 01",
  "Marynarki Polskiej 02",
  "Marynarki Polskiej 03",
  "Marynarki Polskiej 04",
  "Marynarki Polskiej 05",
  "Matarnia PKM 01",
  "Matarnia PKM 02",
  "Matejki 01",
  "Matejki 02",
  "Matejki 02",
  "Matemblewo 01",
  "Mazurska 01",
  "Maćkowy 01",
  "Maćkowy 02",
  "Małomiejska 01",
  "Małomiejska 02",
  "Małopolska 02",
  "Meczet 01",
  "Meczet 02",
  "Meissnera 01",
  "Meissnera 02",
  "Meteorytowa 01",
  "Meteorytowa 02",
  "Miałki Szlak 01",
  "Miałki Szlak 02",
  "Michałki 01",
  "Michałki 02",
  "Mickiewicza 01",
  "Mickiewicza 02",
  "Mickiewicza 03",
  "Mickiewicza 04",
  "Mickiewicza 05",
  "Mickiewicza 06",
  "Migowo 01",
  "Migowo 02",
  "Migowo 03",
  "Migowo 04",
  "Miszewskiego 01",
  "Miszewskiego 02",
  "Mjr Hubala 01",
  "Mjr Hubala 02",
  "Mjr Słabego 02",
  "Modra I 01",
  "Modra II 01",
  "Modra III 01",
  "Modra IV 01",
  "Mostek 01",
  "Mostek 02",
  "Mostostal 01",
  "Mostostal 02",
  "Mostowa 01",
  "Mostowa 02",
  "Muzeum II Wojny Światowej 01",
  "Muzeum II Wojny Światowej 02",
  "Muzeum Narodowe 01",
  "Muzeum Narodowe 02",
  "Muzeum Narodowe 04",
  "Myśliborska 01",
  "Myśliborska 02",
  "Myśliwska 01",
  "Myśliwska 02",
  "Myśliwska 02",
  "Młyńska 02",
  "Na Szańcach 02",
  "Na Wzgórzu 01",
  "Na Wzgórzu 02",
  "Na Zaspę 01",
  "Nad Jarem 01",
  "Nad Jarem 02",
  "Nad Stawem 01",
  "Nad Stawem 02",
  "Nadwiślańska 01",
  "Nadwiślańska 02",
  "Nadwodna 01",
  "Naftowa 01",
  "Naftowa 02",
  "Nałkowskiej 02",
  "Niedziałkowskiego 01",
  "Niedziałkowskiego 02",
  "Niedźwiednik 01",
  "Niegowska 01",
  "Niegowska 02",
  "Niemcewicza 01",
  "Niemcewicza 02",
  "Niepołomicka 01",
  "Niepołomicka 02",
  "Norblina 01",
  "Nowa 01",
  "Nowa 02",
  "Nowa Gdańska 01",
  "Nowa Gdańska 02",
  "Nowatorów 01",
  "Nowatorów 02",
  "Nowatorów 03",
  "Nowatorów 04",
  "Nowiny 01",
  "Nowiny 02",
  "Nowolipie 01",
  "Nowowiejskiego 01",
  "Nowowiejskiego 02",
  "Nowy Port Góreckiego 01",
  "Nowy Port Oliwska 01",
  "Nowy Port Szaniec Zachodni 01",
  "Nowy Port Szaniec Zachodni 02",
  "Nowy Port Zajezdnia 01",
  "Nowy Port Zajezdnia 03",
  "Nowy Świat 01",
  "Nowy Świat 02",
  "Obrońców Westerplatte 01",
  "Obrońców Westerplatte 01",
  "Obrońców Westerplatte 02",
  "Obrońców Westerplatte 02",
  "Obrońców Westerplatte 03",
  "Obrońców Westerplatte 04",
  "Obrońców Westerplatte 05",
  "Obrońców Wybrzeża 01",
  "Obrońców Wybrzeża 01",
  "Obrońców Wybrzeża 02",
  "Obrońców Wybrzeża 02",
  "Oczyszczalnia 01",
  "Oczyszczalnia 02",
  "Oczyszczalnia 03",
  "Odrzańska 01",
  "Odrzańska 02",
  "Odrzańska 03",
  "Odrzańska 04",
  "Ogrodowa 01",
  "Ogrodowa 02",
  'Ogrody Działkowe "Rębiechowo" I 01',
  'Ogrody Działkowe "Rębiechowo" I 02',
  'Ogrody Działkowe "Rębiechowo" II 01',
  'Ogrody Działkowe "Rębiechowo" II 02',
  'Ogrody Działkowe "Rębiechowo" III 01',
  'Ogrody Działkowe "Rębiechowo" III 02',
  "Okopowa 01",
  "Okopowa 02",
  "Okrężna 01",
  "Okrężna 02",
  "Olimpijska 01",
  "Olimpijska 02",
  "Oliwa 01",
  "Oliwa 02",
  "Oliwa 03",
  "Oliwa PKP 01",
  "Oliwa PKP 02",
  "Oliwa PKP 03",
  "Oliwa PKP 04",
  "Oliwa Pętla Tramwajowa 04",
  "Oliwa Pętla Tramwajowa 05",
  "Oliwa Pętla Tramwajowa 06",
  "Oliwa Pętla Tramwajowa 07",
  "Oliwa Pętla Tramwajowa 08",
  "Oliwa Pętla Tramwajowa 09",
  "Oliwa ZOO 01",
  "Oliwska 01",
  "Oliwska 02",
  "Olsztyńska 01",
  "Olsztyńska 02",
  "Olsztyńska 03",
  "Olsztyńska 04",
  "Olszynka - Niwki 01",
  "Olszynka - Szkoła 02",
  "Olszyńska 01",
  "Opacka 01",
  "Opacka 02",
  "Opacka 03",
  "Opacka 04",
  "Opera Bałtycka 01",
  "Opera Bałtycka 02",
  "Opera Bałtycka 03",
  "Opera Bałtycka 04",
  "Opera Bałtycka 05",
  "Opera Bałtycka 06",
  "Opolska 01",
  "Opolska 02",
  "Oriona 01",
  "Oriona 02",
  "Orlinki 01",
  "Orlinki 02",
  "Ornitologów 01",
  "Ornitologów 02",
  "Orunia Górna 01",
  "Osiedle Bursztynowe 02",
  "Osiedle Cytrusowe 01",
  "Osiedle Cytrusowe 02",
  "Osiedle Jary 01",
  "Osiedle Jary 02",
  "Osiedle Kasprowicza 01",
  "Osiedle Kasprowicza 02",
  "Osiedle Olimp 01",
  "Osiedle Olimp 02",
  "Osiedle Olimp 03",
  "Osiedle Piastowskie 02",
  "Osiedle Wejhera 01",
  "Osiedle Wejhera 02",
  "Osiedle Wschód 01",
  "Osiedle Wschód 02",
  "Osiedle Świętokrzyskie 01",
  "Osiedle Świętokrzyskie 02",
  "Osiedle Świętokrzyskie 03",
  "Osowa Obwodnica 01",
  "Osowa Obwodnica 02",
  "Osowa PKP 01",
  "Osowa PKP 02",
  "Osowa PKP 03",
  "Osowa Przesypownia 01",
  "Ostroroga 01",
  "Ostróżek 01",
  "Ostróżek 02",
  "Otomin - Pętla 01",
  "Otomińska 01",
  "Otomińska 02",
  "Otwarta 01",
  "Otwarta 02",
  "Owczarnia 01",
  "Owczarnia 02",
  "PCK 01",
  "PCK 02",
  "Pagórkowa 01",
  "Pagórkowa 02",
  "Paprykowa 01",
  "Paprykowa 02",
  "Park Naukowo - Technologiczny 01",
  "Park Naukowo - Technologiczny 02",
  "Park Reagana 01",
  "Park Reagana 02",
  "Paska 01",
  "Paska 02",
  "Pastelowa 01",
  "Pastelowa 02",
  "Piaskowa 01",
  "Piaskowa 01",
  "Piaskowa 02",
  "Piaskowa 02",
  "Piastowska 01",
  "Piastowska 02",
  "Piastowska 03",
  "Piastowska 04",
  "Piastowska 05",
  "Piastowska 06",
  "Piecewska 01",
  "Piecewska 02",
  "Piekarnicza 01",
  "Piekarnicza 02",
  "Piekarnicza 03",
  "Piekarnicza 04",
  "Pilotów 01",
  "Piotrkowska 01",
  "Piotrkowska 02",
  "Plac Afrodyty 01",
  "Plac Komorowskiego 01",
  "Plac Komorowskiego 02",
  "Plac Komorowskiego 03",
  "Plac Kusocińskiego 02",
  "Plac Solidarności 01",
  "Plac Solidarności 02",
  "Plac Wolności 01",
  "Plac Wolności 02",
  "Plac Wolności 03",
  "Platynowa 01",
  "Platynowa 02",
  "Platynowa 03",
  "Pocztowa 01",
  "Pocztowa 02",
  "Podkarpacka 01",
  "Podkarpacka 02",
  "Pogotowie Ratunkowe 01",
  "Pogotowie Ratunkowe 02",
  "Pohulanka 01",
  "Pohulanka 02",
  "Pohulanka 03",
  "Pohulanka 04",
  "Pokładowa 02",
  "Pokładowa 97",
  "Pole Namiotowe 01",
  "Pole Namiotowe 02",
  "Politechnika 01",
  "Politechnika 02",
  "Polna 01",
  "Polna 02",
  "Pomorska - Osiedle 01",
  "Pomorska - Osiedle 02",
  "Pomorska - Osiedle 03",
  "Pomorska 01",
  "Pomorska 02",
  "Pomorska 03",
  "Pomorska 04",
  "Pomorskie Szkoły Rzemiosł 01",
  "Pomorskie Szkoły Rzemiosł 02",
  "Pomorskie Szkoły Rzemiosł 03",
  "Pomorskie Szkoły Rzemiosł 04",
  "Port Lotniczy 01",
  "Port Lotniczy 02",
  "Port Lotniczy 03",
  "Port Lotniczy 09",
  "Porębskiego 01",
  "Porębskiego 02",
  "Potokowa - Matemblewska 01",
  "Potokowa - Matemblewska 02",
  "Potokowa 01",
  "Potokowa 02",
  "Potokowa 03",
  "Potokowa 04",
  "Potęgowska 01",
  "Potęgowska 02",
  "Powstańców Warszawskich 01",
  "Powstańców Warszawskich 02",
  "Powstańców Warszawy 01",
  "Powstańców Warszawy 02",
  "Poznańska 01",
  "Poznańska 02",
  "Przebiśniegowa 01",
  "Przebiśniegowa 02",
  "Przegalina 01",
  "Przegalińska 01",
  "Przegalińska 02",
  "Przejazd Kolejowy 01",
  "Przejazd Kolejowy 02",
  "Przemian 01",
  "Przemian 02",
  "Przemyska 01",
  "Przemyska 02",
  "Przemyska 03",
  "Przemyska 04",
  "Przemyska 05",
  "Przemysłowa 01",
  "Przemysłowa 02",
  "Przemysłowa 03",
  "Przeróbka 01",
  "Przeróbka 01.",
  "Przeróbka 02",
  "Przeróbka 02.",
  "Przesypownia 02",
  "Przetoczna 01",
  "Przetoczna 02",
  "Przybrzeżna 03",
  "Przychodnia 01",
  "Przylesie 01",
  "Przylesie 02",
  "Przylesie 03",
  "Przymorze SKM 01",
  "Przymorze SKM 02",
  "Przymorze Wielkie 01",
  "Przymorze Wielkie 02",
  "Przyrodników 01",
  "Przyrodników 02",
  "Przystań 01",
  "Przystań 02",
  "Przystań Żeglugi 01",
  "Przystań Żeglugi 02",
  "Przytulna 01",
  "Przywidzka 01",
  "Przywidzka 02",
  "Przywidzka 03",
  "Pszenna 01",
  "Ptasia 01",
  "Ptasia 02",
  "Pólnicy 01",
  "Pólnicy 02",
  "Płocka 01",
  "Płocka 02",
  "Płocka 03",
  "Płocka 04",
  "Płocka 05",
  "Płocka 06",
  "Płowce 01",
  "Płowce 02",
  "Płońska 01",
  "Płońska 02",
  "Radarowa 01",
  "Radiowa 01",
  "Radiowa 02",
  "Radunica 01",
  "Radunica 02",
  "Rafineria 01",
  "Rafineria 02",
  "Rakietowa 01",
  "Rakietowa 02",
  "Rdestowa - Chwaszczyńska 01",
  "Rdestowa - Chwaszczyńska 04",
  "Rdestowa - Leśny Zakątek 02",
  "Reja 01",
  "Reja 01",
  "Reja 02",
  "Reja 02",
  "Rejtana 01 ",
  "Rejtana 02",
  "Reymonta 01",
  "Reymonta 02",
  "Reymonta 02",
  "Rogalińska 01",
  "Rogalińska 02",
  "Rogozińskiego 01",
  "Rondo Bursztynowe 01",
  "Rondo Bursztynowe 02",
  "Rondo Kaszubskie 01",
  "Rondo Kaszubskie 02",
  "Rondo Kociewskie 01",
  "Rotmanka - Rondo 01",
  "Rozstaje 04",
  "Rozstaje 05",
  "Rozłogi 01",
  "Rybacka 01",
  "Rybaki Górne 01",
  "Rybołowców 02",
  "Rynarzewo 01",
  "Rynarzewo 02",
  "Rzeczypospolitej 01",
  "Rzeczypospolitej 02",
  "Rzeźnicka 01",
  "Równa 01",
  "Rębiechowo PKP 01",
  "Rębiechowo PKP 02",
  "Rębowo 01",
  "Rębowo 02",
  'SDO "Złota Jesień" 01',
  'Sanatorium "Leśnik" 01',
  "Sandomierska 01",
  "Sandomierska 02",
  "Sarnia 01",
  "Sarnia 01",
  "Sarnia 02",
  'Schronisko dla zwierząt "Promyk" 01',
  'Schronisko dla zwierząt "Promyk" 02',
  "Schuberta 01",
  "Schuberta 02",
  "Schumana 01",
  "Schumana 02",
  "Sezonowa 01",
  "Sezonowa 02",
  "Siedlce 01",
  "Siedlce 02",
  "Siedlce 03",
  "Siedlce 04",
  "Siedlce 05",
  "Siedlce 06",
  "Siedlicka 01",
  "Siedlicka 02",
  "Sienkiewicza 01",
  "Sienkiewicza 02",
  "Siennicka 01",
  "Siennicka 02",
  "Sierpowa 01",
  "Sikorskiego 01",
  "Sikorskiego 01",
  "Sikorskiego 02",
  "Sikorskiego 03",
  "Sikorskiego 03",
  "Sikorskiego 04",
  "Sikorskiego 04",
  "Sikorskiego 05",
  "Skarżyńskiego 01",
  "Skarżyńskiego 02",
  "Skrajna 01",
  "Skrajna 02",
  "Smolna 01",
  "Smolna 02",
  "Smoluchowskiego 01",
  "Smoluchowskiego 02",
  "Sobieszewo 01",
  "Sobieszewska 01",
  "Sobieszewska 02",
  "Sobótki 01",
  "Sobótki 02",
  "Sopocka 01",
  "Sopocka 02",
  "Sopocka 04",
  "Sopot PKP - Marynarzy 01",
  "Sopot PKP - Marynarzy 02",
  "Sopot PKP - Niepodległości 01",
  "Sopot PKP - Niepodległości 02",
  "Sopot PKP 02",
  "Spadochroniarzy 01",
  "Spadochroniarzy 02",
  "Sportowa 01",
  "Sportowa 02",
  "Srebrna 01",
  "Srebrna 02",
  "Srebrna 03",
  "Stadion 03",
  "Stadion 04",
  "Stadion 05",
  "Stadion 06",
  "Stadion Energa Gdańsk 01",
  "Stadion Energa Gdańsk 02",
  "Stara Piła 09",
  "Stare Szkoty 01",
  "Stare Szkoty 02",
  "Starochwaszczyńska 01",
  "Starochwaszczyńska 02",
  "Starogardzka 01",
  "Starogardzka 03",
  "Starowiejska 01",
  "Starowiejska 02",
  "Startowa 01",
  "Startowa 02",
  "Startowa 03",
  "Startowa 04",
  "Staw Wróbla 01",
  "Staw Wróbla 02",
  "Steczka 01",
  "Steczka 02",
  "Sternicza 01",
  "Stocznia Północna 01",
  "Stocznia Północna 02",
  "Stocznia Północna 03",
  "Stocznia Północna 04",
  "Stocznia SKM 01",
  "Stocznia SKM 02",
  "Stogi 02",
  "Stogi 02.",
  "Stogi 03",
  "Stogi 03.",
  "Stogi 04",
  "Stogi 06",
  "Stogi 08",
  "Stogi Plaża 01",
  "Stogi Plaża 02",
  "Stokrotki 01",
  "Stolema 01",
  "Stolema 02",
  "Stolema 03",
  "Stolema 04",
  "Strzelnica 01",
  "Strzelnica 02",
  "Strzyża PKM 01",
  "Strzyża PKM 02",
  "Strzyża PKM 03",
  "Strzyża PKM 04",
  "Strzyża PKM 05",
  "Stężycka 01",
  "Subisława 01",
  "Subisława 02",
  "Subisława 03",
  "Suchanino 01",
  "Suchanino 02",
  "Sucharskiego - PKP 01",
  "Sucharskiego - PKP 02",
  "Sucharskiego 01",
  "Sucharskiego 02",
  "Sucharskiego 03",
  "Sucharskiego 04",
  "Sulmin 16",
  "Sulmin 17",
  "Sulmińska 01",
  "Sulmińska 14",
  "Swojska 01",
  "Swojska 02",
  "Swojska 03",
  "Swojska 04",
  "Szadółki 01",
  "Szadółki 02",
  "Szadółki Obwodnica 01",
  "Szadółki Obwodnica 02",
  "Szafranowa 01",
  "Szafranowa 02",
  "Szczęśliwa 01",
  "Szczęśliwa 02",
  "Szkolna 01 ",
  "Szkolna 02 ",
  "Szkoła 01",
  "Szkoła 02",
  "Szkoła 10",
  "Szkoła Metropolitalna 01",
  "Szkoła Podstawowa nr 6 01",
  "Szlachecka 01",
  "Szlachecka 02",
  "Szmaragdowa 01",
  "Szmaragdowa 01",
  "Szmaragdowa 02",
  "Szpital Marynarki Wojennej 01",
  "Szpital Marynarki Wojennej 02",
  "Szpital Zakaźny 01",
  "Szpital Zakaźny 02",
  "Sztutowska 01",
  "Szybowcowa 01",
  "Szybowcowa 02",
  "Sówki 01",
  "Sówki 02",
  "Sąsiedzka 01",
  "Sąsiedzka 02",
  "Słowackiego 01",
  "Słowackiego Działki 01",
  "Słowackiego Działki 02",
  "Tarcice 01",
  "Tarcice 02",
  "Teatr Miniatura / Radio Gdańsk 03",
  "Teatr Miniatura / Radio Gdańsk 04",
  "Telewizyjna 01",
  "Telewizyjna 02",
  "Terminal - Cargo 01",
  "Terminal - Cargo 02",
  "Terminal DCT 01",
  "Tetmajera 01",
  "Tetmajera 02",
  "Topazowa 01",
  "Topazowa 02",
  "Toruńska 01",
  "Toruńska 02",
  "Trakt Gdański 01",
  "Trakt Konny 19",
  "Trakt Konny 20",
  "Transportowców 01",
  "Transportowców 02",
  "Traugutta 01",
  "Traugutta 02",
  "Traugutta 03",
  "Trawki 01",
  "Trawki 02",
  "Trałowa - Szkoła 01",
  "Trałowa - Szkoła 02",
  "Turystyczna 01",
  "Turystyczna 02",
  "Twarda 01",
  "Twarda 02",
  "Twierdza Wisłoujście 01",
  "Twierdza Wisłoujście 02",
  "Tysiąclecia 01",
  "Tysiąclecia 02",
  "Tęczowa 01",
  "Tęczowa 02",
  "Uczniowska 01",
  "Uczniowska 02",
  "Ujeścisko 01",
  "Ujeścisko 03",
  "Ujeścisko 04",
  "Ujeścisko 06",
  "Ukośna 01",
  "Ukośna 02",
  "Unimor 01",
  "Unimor 02",
  "Uniwersyteckie Centrum Kliniczne 02",
  "Uniwersytet Gdański 01",
  "Uniwersytet Gdański 01",
  "Uniwersytet Gdański 02",
  "Uniwersytet Gdański 02",
  "Uniwersytet Gdański 03",
  "Uniwersytet Gdański 04",
  "Uniwersytet Medyczny 01",
  "Uniwersytet Medyczny 02",
  "Uniwersytet Medyczny 03",
  "Uniwersytet Medyczny 04",
  "Uphagena 01",
  "Uranowa 01",
  "Urząd Dozoru Technicznego 01",
  "Urząd Miejski 01",
  "Urząd Miejski 02",
  "Urząd Skarbowy 01",
  "Uzdrowiskowa 01",
  "Uzdrowiskowa 02",
  "Wagnera 01",
  "Wagnera 02",
  "Waląga 01",
  "Waląga 02",
  "Warneńska 01",
  "Warneńska 02",
  "Warneńska 03",
  "Warneńska 04",
  "Wały Piastowskie  01",
  "Wały Piastowskie 02",
  "Wczasy 01",
  "Westerplatte 01",
  "Wiczlińska 02",
  "Wiejska 01",
  "Wieżycka 01",
  "Wieżycka 02",
  "Wilanowska 01",
  "Wilanowska 02",
  "Wilanowska 03",
  "Wilanowska 04",
  "Wileńska 01",
  "Wiśniewskiego 01",
  "Wiśniewskiego 02",
  "Wodnika 01",
  "Wodnika 02",
  "Wojska Polskiego 01",
  "Wojska Polskiego 01",
  "Wojska Polskiego 02",
  "Wojska Polskiego 03",
  "Wojska Polskiego 04",
  "Wojska Polskiego 05",
  "Worcella 01",
  "Worcella 02",
  "Wołkowyska 01",
  "Wołkowyska 02",
  "Wrzeszcz PKP 01",
  "Wrzeszcz PKP 03",
  "Wrzeszcz PKP 04",
  "Wrzeszcz PKP 05",
  "Wrzeszcz PKP 06",
  "Wrzosowe Wzgórze 15",
  "Wrzosowe Wzgórze 18",
  "Wróbla 01",
  "Wybickiego 01",
  "Wyczółkowskiego 01",
  "Wyczółkowskiego 02",
  "Wysockiego 01",
  "Wysockiego 02",
  "Wyspiańskiego 01",
  "Wyspiańskiego 02",
  "Wyspiańskiego 03",
  "Wyspiańskiego 04",
  "Wyzwolenia 01",
  "Wyzwolenia 02",
  "Węgorzowa 01",
  "Węgorzowa 02",
  "Węzeł Elbląska 01",
  "Węzeł Elbląska 02",
  "Węzeł Groddecka 01",
  "Węzeł Karczemki 01",
  "Węzeł Karczemki 02",
  "Węzeł Kliniczna 01",
  "Węzeł Kliniczna 02",
  "Węzeł Lipce 02",
  "Władysława IV 01",
  "Władysława IV 01",
  "Władysława IV 02",
  "Władysława IV 02",
  "Zabornia 01",
  "Zabornia 02",
  "Zabornia 03",
  "Zabornia 04",
  "Zabornia 05",
  "Zabornia 06",
  "Zabytkowa 01",
  "Zabytkowa 02",
  "Zacna 01",
  "Zacna 02",
  "Zagroble 01",
  "Zagroble 02",
  "Zajezdnia 01",
  "Zajezdnia 02",
  "Zajezdnia 03",
  "Zajezdnia 04",
  "Zajezdnia NOWY PORT T1",
  "Zajezdnia NOWY PORT T2",
  "Zajezdnia WRZESZCZ T1",
  "Zajezdnia WRZESZCZ T2",
  "Zakoniczyn 01",
  "Zakopiańska 01",
  "Zakopiańska 02",
  "Zakopiańska 02.",
  "Zakopiańska 03",
  "Zamenhofa 01",
  "Zamenhofa 02",
  "Zamenhofa 03",
  "Zamenhofa 04",
  "Zaspa - Szpital 01",
  "Zaspa - Szpital 02",
  "Zaspa 01",
  "Zaspa 02",
  "Zaspa 03",
  "Zaspa 04",
  "Zaspa SKM 01",
  "Zaspa SKM 02",
  "Zastawna 01",
  "Zastawna 02",
  "Zawodzie 01",
  "Zbieżna 02",
  "Zespół Szkół Morskich 01",
  "Zespół Szkół Morskich 02",
  "Zeusa 01",
  "Zeusa 02",
  "Zielony Stok 01",
  "Zielony Stok 02",
  "Zimna 01",
  "Zimna 01.",
  "Zimna 02",
  "Zimna 02.",
  "Zwierzyniecka 01",
  "Złota Karczma 01",
  "Złota Karczma 02",
  "al. Płażyńskiego 01",
  "al. Płażyńskiego 02",
  "al. Płażyńskiego 03",
  "al. Płażyńskiego 04",
  "al. Płażyńskiego 05",
  "al. Płażyńskiego 06",
  "Łabędzia 01",
  "Łabędzia 02",
  "Łabędzia 03",
  "Łabędzia 04",
  "Łagiewniki 01",
  "Łanowa I 01",
  "Łanowa II 01",
  "Łanowa III 01",
  "Łanowa IV 01",
  "Łapińska 01",
  "Łapińska 02",
  "Łostowice Świętokrzyska 01",
  "Łostowice Świętokrzyska 02",
  "Łostowice Świętokrzyska 04",
  "Łostowice Świętokrzyska 05",
  "Łostowice Świętokrzyska 06",
  "Łowicka 01",
  "Łowicka 02",
  "Łódzka 01",
  "Łódzka 02",
  "Łąkowa 01",
  "Łąkowa 02",
  "Łęczycka 01",
  "Łęczycka 02",
  "Śnieżna 01",
  "Śnieżna 02",
  "Śnieżna 03",
  "Śnieżna 04",
  "Śródmieście SKM 01",
  "Śródmieście SKM 02",
  "Śródmieście SKM 03",
  "Śródmieście SKM 04",
  "Św. Wojciech 01",
  "Św. Wojciech 02",
  "Świbnieńska I 01",
  "Świbnieńska I 02",
  "Świbnieńska II 01",
  "Świbnieńska II 02",
  "Świbnieńska III 01",
  "Świbnieńska III 02",
  "Świętokrzyska 01",
  "Świętokrzyska 02",
  "Źródlana 01",
  "Źródlana 02",
  "Źródło Marii 02",
  "Żabi Kruk 01",
  "Żabi Kruk 02",
  "Żabi Kruk 03",
  "Żabi Kruk 04",
  "Żabianka SKM 01",
  "Żabianka SKM 02",
  "Żabianka SKM 03",
  "Żaglowa - AmberExpo 01",
  "Żaglowa - AmberExpo 02",
  "Żaglowa - AmberExpo 03",
  "Żaglowa - AmberExpo 04",
  "Żarnowiecka 02",
  "Żwirki i Wigury 01",
  "Żwirki i Wigury 01",
  "Żwirki i Wigury 02",
  "Żwirki i Wigury 02",
  "Żwirki i Wigury 03",
  "Życzliwa 01",
  "Życzliwa 02",
];

autocomplete(stopInput, busStops);
